# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/global_def.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/RF.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/PC.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/ctrl_encode_def.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/NPC.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/mux4.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/mux2.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/IR.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/im_4k.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/flopr.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/EXT.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/dm_4k.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/instruction_def.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/ctrl.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/alu.v
  C:/Users/Administrator/Desktop/project_1/project_1.srcs/sources_1/new/mips.v
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_dir C:/Users/Administrator/Desktop/project_1 [current_project]
catch { write_hwdef -file mips.hwdef }
synth_design -top mips -part xc7a100tcsg324-1
write_checkpoint mips.dcp
report_utilization -file mips_utilization_synth.rpt -pb mips_utilization_synth.pb
